version: '3.8'

services:
 
  db:
    image: postgres:latest
    container_name: avisala_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avisaladb
    ports:
      - "2222:5432" 

  app:
    build: .
    container_name: avisala_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
    network_mode: "host"